feat: 修改为静态模式

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -44,13 +44,25 @@ jobs:
       - name: Build
         env:
           NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
-          CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}
+          NEXT_PUBLIC_CLERK_SIGN_IN_URL: /sign-in
+          NEXT_PUBLIC_CLERK_SIGN_UP_URL: /sign-up
+          NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL: /
+          NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL: /
         run: pnpm build
 
       - name: Configure Pages
         uses: actions/configure-pages@v3
         with:
           static_site_generator: next
+
+      - name: Check output directory
+        run: |
+          ls -la
+          echo "Checking for out directory:"
+          ls -la out || echo "out directory not found"
+          ls -la
+          echo "Checking for out directory:"
+          ls -la out || echo "out directory not found"
 
       - name: Upload artifact
         uses: actions/upload-pages-artifact@v3
